// Manifest license

#ifndef CREN_MANIFEST_LICENSE_H
#define CREN_MANIFEST_LICENSE_H

/// @brief License type for manifest SPDX 3.20 <https://github.com/spdx/license-list-data/tree/v3.20>
typedef enum license_t license_t;

enum license_t
{
    /// @brief Unknown license
    LICENSE_UNKNOWN = -1,
    /// @brief Unset
    LICENSE_NONE = 0,
    LICENSE_0BSD,                                 // 0BSD
    LICENSE_3D_SLICER_1_0,                        // 3D-Slicer-1.0
    LICENSE_AAL,                                  // AAL
    LICENSE_ABSTYLES,                             // Abstyles
    LICENSE_ADACORE_DOC,                          // AdaCore-doc
    LICENSE_ADOBE_2006,                           // Adobe-2006
    LICENSE_ADOBE_DISPLAY_POSTSCRIPT,             // Adobe-Display-PostScript
    LICENSE_ADOBE_GLYPH,                          // Adobe-Glyph
    LICENSE_ADOBE_UTOPIA,                         // Adobe-Utopia
    LICENSE_ADSL,                                 // ADSL
    LICENSE_AFL_1_1,                              // AFL-1.1
    LICENSE_AFL_1_2,                              // AFL-1.2
    LICENSE_AFL_2_0,                              // AFL-2.0
    LICENSE_AFL_2_1,                              // AFL-2.1
    LICENSE_AFL_3_0,                              // AFL-3.0
    LICENSE_AFMPARSE,                             // Afmparse
    LICENSE_AGPL_1_0,                             // AGPL-1.0
    LICENSE_AGPL_1_0_ONLY,                        // AGPL-1.0-only
    LICENSE_AGPL_1_0_OR_LATER,                    // AGPL-1.0-or-later
    LICENSE_AGPL_3_0,                             // AGPL-3.0
    LICENSE_AGPL_3_0_ONLY,                        // AGPL-3.0-only
    LICENSE_AGPL_3_0_OR_LATER,                    // AGPL-3.0-or-later
    LICENSE_ALADDIN,                              // Aladdin
    LICENSE_AMD_NEWLIB,                           // AMD-newlib
    LICENSE_AMDPLPA,                              // AMDPLPA
    LICENSE_AML,                                  // AML
    LICENSE_AML_GLSLANG,                          // AML-glslang
    LICENSE_AMPAS,                                // AMPAS
    LICENSE_ANTLR_PD,                             // ANTLR-PD
    LICENSE_ANTLR_PD_FALLBACK,                    // ANTLR-PD-fallback
    LICENSE_ANY_OSI,                              // any-OSI
    LICENSE_ANY_OSI_PERL_MODULES,                 // any-OSI-perl-modules
    LICENSE_APACHE_1_0,                           // Apache-1.0
    LICENSE_APACHE_1_1,                           // Apache-1.1
    LICENSE_APACHE_2_0,                           // Apache-2.0
    LICENSE_APAFML,                               // APAFML
    LICENSE_APL_1_0,                              // APL-1.0
    LICENSE_APP_S2P,                              // App-s2p
    LICENSE_APSL_1_0,                             // APSL-1.0
    LICENSE_APSL_1_1,                             // APSL-1.1
    LICENSE_APSL_1_2,                             // APSL-1.2
    LICENSE_APSL_2_0,                             // APSL-2.0
    LICENSE_ARPHIC_1999,                          // Arphic-1999
    LICENSE_ARTISTIC_1_0,                         // Artistic-1.0
    LICENSE_ARTISTIC_1_0_CL8,                     // Artistic-1.0-cl8
    LICENSE_ARTISTIC_1_0_PERL,                    // Artistic-1.0-Perl
    LICENSE_ARTISTIC_2_0,                         // Artistic-2.0
    LICENSE_ASWF_DIGITAL_ASSETS_1_0,              // ASWF-Digital-Assets-1.0
    LICENSE_ASWF_DIGITAL_ASSETS_1_1,              // ASWF-Digital-Assets-1.1
    LICENSE_BAEKMUK,                              // Baekmuk
    LICENSE_BAHYPH,                               // Bahyph
    LICENSE_BARR,                                 // Barr
    LICENSE_BCRYPT_SOLAR_DESIGNER,                // bcrypt-Solar-Designer
    LICENSE_BEERWARE,                             // Beerware
    LICENSE_BITSTREAM_CHARTER,                    // Bitstream-Charter
    LICENSE_BITSTREAM_VERA,                       // Bitstream-Vera
    LICENSE_BITTORRENT_1_0,                       // BitTorrent-1.0
    LICENSE_BITTORRENT_1_1,                       // BitTorrent-1.1
    LICENSE_BLESSING,                             // blessing
    LICENSE_BLUEOAK_1_0_0,                        // BlueOak-1.0.0
    LICENSE_BOEHM_GC,                             // Boehm-GC
    LICENSE_BOEHM_GC_WITHOUT_FEE,                 // Boehm-GC-without-fee
    LICENSE_BORCEUX,                              // Borceux
    LICENSE_BRIAN_GLADMAN_2_CLAUSE,               // Brian-Gladman-2-Clause
    LICENSE_BRIAN_GLADMAN_3_CLAUSE,               // Brian-Gladman-3-Clause
    LICENSE_BSD_1_CLAUSE,                         // BSD-1-Clause
    LICENSE_BSD_2_CLAUSE,                         // BSD-2-Clause
    LICENSE_BSD_2_CLAUSE_DARWIN,                  // BSD-2-Clause-Darwin
    LICENSE_BSD_2_CLAUSE_FIRST_LINES,             // BSD-2-Clause-first-lines
    LICENSE_BSD_2_CLAUSE_FREEBSD,                 // BSD-2-Clause-FreeBSD
    LICENSE_BSD_2_CLAUSE_NETBSD,                  // BSD-2-Clause-NetBSD
    LICENSE_BSD_2_CLAUSE_PATENT,                  // BSD-2-Clause-Patent
    LICENSE_BSD_2_CLAUSE_VIEWS,                   // BSD-2-Clause-Views
    LICENSE_BSD_3_CLAUSE,                         // BSD-3-Clause
    LICENSE_BSD_3_CLAUSE_ACPICA,                  // BSD-3-Clause-acpica
    LICENSE_BSD_3_CLAUSE_ATTRIBUTION,             // BSD-3-Clause-Attribution
    LICENSE_BSD_3_CLAUSE_CLEAR,                   // BSD-3-Clause-Clear
    LICENSE_BSD_3_CLAUSE_FLEX,                    // BSD-3-Clause-flex
    LICENSE_BSD_3_CLAUSE_HP,                      // BSD-3-Clause-HP
    LICENSE_BSD_3_CLAUSE_LBNL,                    // BSD-3-Clause-LBNL
    LICENSE_BSD_3_CLAUSE_MODIFICATION,            // BSD-3-Clause-Modification
    LICENSE_BSD_3_CLAUSE_NO_MILITARY_LICENSE,     // BSD-3-Clause-No-Military-License
    LICENSE_BSD_3_CLAUSE_NO_NUCLEAR_LICENSE,      // BSD-3-Clause-No-Nuclear-License
    LICENSE_BSD_3_CLAUSE_NO_NUCLEAR_LICENSE_2014, // BSD-3-Clause-No-Nuclear-License-2014
    LICENSE_BSD_3_CLAUSE_NO_NUCLEAR_WARRANTY,     // BSD-3-Clause-No-Nuclear-Warranty
    LICENSE_BSD_3_CLAUSE_OPEN_MPI,                // BSD-3-Clause-Open-MPI
    LICENSE_BSD_3_CLAUSE_SUN,                     // BSD-3-Clause-Sun
    LICENSE_BSD_4_CLAUSE,                         // BSD-4-Clause
    LICENSE_BSD_4_CLAUSE_SHORTENED,               // BSD-4-Clause-Shortened
    LICENSE_BSD_4_CLAUSE_UC,                      // BSD-4-Clause-UC
    LICENSE_BSD_4_3RENO,                          // BSD-4.3RENO
    LICENSE_BSD_4_3TAHOE,                         // BSD-4.3TAHOE
    LICENSE_BSD_ADVERTISING_ACKNOWLEDGEMENT,      // BSD-Advertising-Acknowledgement
    LICENSE_BSD_ATTRIBUTION_HPND_DISCLAIMER,      // BSD-Attribution-HPND-disclaimer
    LICENSE_BSD_INFERNO_NETTVERK,                 // BSD-Inferno-Nettverk
    LICENSE_BSD_PROTECTION,                       // BSD-Protection
    LICENSE_BSD_SOURCE_BEGINNING_FILE,            // BSD-Source-beginning-file
    LICENSE_BSD_SOURCE_CODE,                      // BSD-Source-Code
    LICENSE_BSD_SYSTEMICS,                        // BSD-Systemics
    LICENSE_BSD_SYSTEMICS_W3WORKS,                // BSD-Systemics-W3Works
    LICENSE_BSL_1_0,                              // BSL-1.0
    LICENSE_BUSL_1_1,                             // BUSL-1.1
    LICENSE_BZIP2_1_0_5,                          // bzip2-1.0.5
    LICENSE_BZIP2_1_0_6,                          // bzip2-1.0.6
    LICENSE_C_UDA_1_0,                            // C-UDA-1.0
    LICENSE_CAL_1_0,                              // CAL-1.0
    LICENSE_CAL_1_0_COMBINED_WORK_EXCEPTION,      // CAL-1.0-Combined-Work-Exception
    LICENSE_CALDERA,                              // Caldera
    LICENSE_CALDERA_NO_PREAMBLE,                  // Caldera-no-preamble
    LICENSE_CATHARON,                             // Catharon
    LICENSE_CATOSL_1_1,                           // CATOSL-1.1
    LICENSE_CC_BY_1_0,                            // CC-BY-1.0
    LICENSE_CC_BY_2_0,                            // CC-BY-2.0
    LICENSE_CC_BY_2_5,                            // CC-BY-2.5
    LICENSE_CC_BY_2_5_AU,                         // CC-BY-2.5-AU
    LICENSE_CC_BY_3_0,                            // CC-BY-3.0
    LICENSE_CC_BY_3_0_AT,                         // CC-BY-3.0-AT
    LICENSE_CC_BY_3_0_AU,                         // CC-BY-3.0-AU
    LICENSE_CC_BY_3_0_DE,                         // CC-BY-3.0-DE
    LICENSE_CC_BY_3_0_IGO,                        // CC-BY-3.0-IGO
    LICENSE_CC_BY_3_0_NL,                         // CC-BY-3.0-NL
    LICENSE_CC_BY_3_0_US,                         // CC-BY-3.0-US
    LICENSE_CC_BY_4_0,                            // CC-BY-4.0
    LICENSE_CC_BY_NC_1_0,                         // CC-BY-NC-1.0
    LICENSE_CC_BY_NC_2_0,                         // CC-BY-NC-2.0
    LICENSE_CC_BY_NC_2_5,                         // CC-BY-NC-2.5
    LICENSE_CC_BY_NC_3_0,                         // CC-BY-NC-3.0
    LICENSE_CC_BY_NC_3_0_DE,                      // CC-BY-NC-3.0-DE
    LICENSE_CC_BY_NC_4_0,                         // CC-BY-NC-4.0
    LICENSE_CC_BY_NC_ND_1_0,                      // CC-BY-NC-ND-1.0
    LICENSE_CC_BY_NC_ND_2_0,                      // CC-BY-NC-ND-2.0
    LICENSE_CC_BY_NC_ND_2_5,                      // CC-BY-NC-ND-2.5
    LICENSE_CC_BY_NC_ND_3_0,                      // CC-BY-NC-ND-3.0
    LICENSE_CC_BY_NC_ND_3_0_DE,                   // CC-BY-NC-ND-3.0-DE
    LICENSE_CC_BY_NC_ND_3_0_IGO,                  // CC-BY-NC-ND-3.0-IGO
    LICENSE_CC_BY_NC_ND_4_0,                      // CC-BY-NC-ND-4.0
    LICENSE_CC_BY_NC_SA_1_0,                      // CC-BY-NC-SA-1.0
    LICENSE_CC_BY_NC_SA_2_0,                      // CC-BY-NC-SA-2.0
    LICENSE_CC_BY_NC_SA_2_0_DE,                   // CC-BY-NC-SA-2.0-DE
    LICENSE_CC_BY_NC_SA_2_0_FR,                   // CC-BY-NC-SA-2.0-FR
    LICENSE_CC_BY_NC_SA_2_0_UK,                   // CC-BY-NC-SA-2.0-UK
    LICENSE_CC_BY_NC_SA_2_5,                      // CC-BY-NC-SA-2.5
    LICENSE_CC_BY_NC_SA_3_0,                      // CC-BY-NC-SA-3.0
    LICENSE_CC_BY_NC_SA_3_0_DE,                   // CC-BY-NC-SA-3.0-DE
    LICENSE_CC_BY_NC_SA_3_0_IGO,                  // CC-BY-NC-SA-3.0-IGO
    LICENSE_CC_BY_NC_SA_4_0,                      // CC-BY-NC-SA-4.0
    LICENSE_CC_BY_ND_1_0,                         // CC-BY-ND-1.0
    LICENSE_CC_BY_ND_2_0,                         // CC-BY-ND-2.0
    LICENSE_CC_BY_ND_2_5,                         // CC-BY-ND-2.5
    LICENSE_CC_BY_ND_3_0,                         // CC-BY-ND-3.0
    LICENSE_CC_BY_ND_3_0_DE,                      // CC-BY-ND-3.0-DE
    LICENSE_CC_BY_ND_4_0,                         // CC-BY-ND-4.0
    LICENSE_CC_BY_SA_1_0,                         // CC-BY-SA-1.0
    LICENSE_CC_BY_SA_2_0,                         // CC-BY-SA-2.0
    LICENSE_CC_BY_SA_2_0_UK,                      // CC-BY-SA-2.0-UK
    LICENSE_CC_BY_SA_2_1_JP,                      // CC-BY-SA-2.1-JP
    LICENSE_CC_BY_SA_2_5,                         // CC-BY-SA-2.5
    LICENSE_CC_BY_SA_3_0,                         // CC-BY-SA-3.0
    LICENSE_CC_BY_SA_3_0_AT,                      // CC-BY-SA-3.0-AT
    LICENSE_CC_BY_SA_3_0_DE,                      // CC-BY-SA-3.0-DE
    LICENSE_CC_BY_SA_3_0_IGO,                     // CC-BY-SA-3.0-IGO
    LICENSE_CC_BY_SA_4_0,                         // CC-BY-SA-4.0
    LICENSE_CC_PDDC,                              // CC-PDDC
    LICENSE_CC_PDM_1_0,                           // CC-PDM-1.0
    LICENSE_CC_SA_1_0,                            // CC-SA-1.0
    LICENSE_CC0_1_0,                              // CC0-1.0
    LICENSE_CDDL_1_0,                             // CDDL-1.0
    LICENSE_CDDL_1_1,                             // CDDL-1.1
    LICENSE_CDL_1_0,                              // CDL-1.0
    LICENSE_CDLA_PERMISSIVE_1_0,                  // CDLA-Permissive-1.0
    LICENSE_CDLA_PERMISSIVE_2_0,                  // CDLA-Permissive-2.0
    LICENSE_CDLA_SHARING_1_0,                     // CDLA-Sharing-1.0
    LICENSE_CECILL_1_0,                           // CECILL-1.0
    LICENSE_CECILL_1_1,                           // CECILL-1.1
    LICENSE_CECILL_2_0,                           // CECILL-2.0
    LICENSE_CECILL_2_1,                           // CECILL-2.1
    LICENSE_CECILL_B,                             // CECILL-B
    LICENSE_CECILL_C,                             // CECILL-C
    LICENSE_CERN_OHL_1_1,                         // CERN-OHL-1.1
    LICENSE_CERN_OHL_1_2,                         // CERN-OHL-1.2
    LICENSE_CERN_OHL_P_2_0,                       // CERN-OHL-P-2.0
    LICENSE_CERN_OHL_S_2_0,                       // CERN-OHL-S-2.0
    LICENSE_CERN_OHL_W_2_0,                       // CERN-OHL-W-2.0
    LICENSE_CFITSIO,                              // CFITSIO
    LICENSE_CHECK_CVS,                            // check-cvs
    LICENSE_CHECKMK,                              // checkmk
    LICENSE_CLARTISTIC,                           // ClArtistic
    LICENSE_CLIPS,                                // Clips
    LICENSE_CMU_MACH,                             // CMU-Mach
    LICENSE_CMU_MACH_NODOC,                       // CMU-Mach-nodoc
    LICENSE_CNRI_JYTHON,                          // CNRI-Jython
    LICENSE_CNRI_PYTHON,                          // CNRI-Python
    LICENSE_CNRI_PYTHON_GPL_COMPATIBLE,           // CNRI-Python-GPL-Compatible
    LICENSE_COIL_1_0,                             // COIL-1.0
    LICENSE_COMMUNITY_SPEC_1_0,                   // Community-Spec-1.0
    LICENSE_CONDOR_1_1,                           // Condor-1.1
    LICENSE_COPYLEFT_NEXT_0_3_0,                  // copyleft-next-0.3.0
    LICENSE_COPYLEFT_NEXT_0_3_1,                  // copyleft-next-0.3.1
    LICENSE_CORNELL_LOSSLESS_JPEG,                // Cornell-Lossless-JPEG
    LICENSE_CPAL_1_0,                             // CPAL-1.0
    LICENSE_CPL_1_0,                              // CPL-1.0
    LICENSE_CPOL_1_02,                            // CPOL-1.02
    LICENSE_CRONYX,                               // Cronyx
    LICENSE_CROSSWORD,                            // Crossword
    LICENSE_CRYSTALSTACKER,                       // CrystalStacker
    LICENSE_CUA_OPL_1_0,                          // CUA-OPL-1.0
    LICENSE_CUBE,                                 // Cube
    LICENSE_CURL,                                 // curl
    LICENSE_CVE_TOU,                              // cve-tou
    LICENSE_D_FSL_1_0,                            // D-FSL-1.0
    LICENSE_DEC_3_CLAUSE,                         // DEC-3-Clause
    LICENSE_DIFFMARK,                             // diffmark
    LICENSE_DL_DE_BY_2_0,                         // DL-DE-BY-2.0
    LICENSE_DL_DE_ZERO_2_0,                       // DL-DE-ZERO-2.0
    LICENSE_DOC,                                  // DOC
    LICENSE_DOCBOOK_SCHEMA,                       // DocBook-Schema
    LICENSE_DOCBOOK_STYLESHEET,                   // DocBook-Stylesheet
    LICENSE_DOCBOOK_XML,                          // DocBook-XML
    LICENSE_DOTSEQN,                              // Dotseqn
    LICENSE_DRL_1_0,                              // DRL-1.0
    LICENSE_DRL_1_1,                              // DRL-1.1
    LICENSE_DSDP,                                 // DSDP
    LICENSE_DTOA,                                 // dtoa
    LICENSE_DVIPDFM,                              // dvipdfm
    LICENSE_ECL_1_0,                              // ECL-1.0
    LICENSE_ECL_2_0,                              // ECL-2.0
    LICENSE_ECOS_2_0,                             // eCos-2.0
    LICENSE_EFL_1_0,                              // EFL-1.0
    LICENSE_EFL_2_0,                              // EFL-2.0
    LICENSE_EGENIX,                               // eGenix
    LICENSE_ELASTIC_2_0,                          // Elastic-2.0
    LICENSE_ENTESSA,                              // Entessa
    LICENSE_EPICS,                                // EPICS
    LICENSE_EPL_1_0,                              // EPL-1.0
    LICENSE_EPL_2_0,                              // EPL-2.0
    LICENSE_ERLPL_1_1,                            // ErlPL-1.1
    LICENSE_ETALAB_2_0,                           // etalab-2.0
    LICENSE_EUDATAGRID,                           // EUDatagrid
    LICENSE_EUPL_1_0,                             // EUPL-1.0
    LICENSE_EUPL_1_1,                             // EUPL-1.1
    LICENSE_EUPL_1_2,                             // EUPL-1.2
    LICENSE_EUROSYM,                              // Eurosym
    LICENSE_FAIR,                                 // Fair
    LICENSE_FBM,                                  // FBM
    LICENSE_FDK_AAC,                              // FDK-AAC
    LICENSE_FERGUSON_TWOFISH,                     // Ferguson-Twofish
    LICENSE_FRAMEWORX_1_0,                        // Frameworx-1.0
    LICENSE_FREEBSD_DOC,                          // FreeBSD-DOC
    LICENSE_FREEIMAGE,                            // FreeImage
    LICENSE_FSFAP,                                // FSFAP
    LICENSE_FSFAP_NO_WARRANTY_DISCLAIMER,         // FSFAP-no-warranty-disclaimer
    LICENSE_FSFUL,                                // FSFUL
    LICENSE_FSFULLR,                              // FSFULLR
    LICENSE_FSFULLRWD,                            // FSFULLRWD
    LICENSE_FTL,                                  // FTL
    LICENSE_FURUSETH,                             // Furuseth
    LICENSE_FWLW,                                 // fwlw
    LICENSE_GCR_DOCS,                             // GCR-docs
    LICENSE_GD,                                   // GD
    LICENSE_GENERIC_XTS,                          // generic-xts
    LICENSE_GFDL_1_1,                             // GFDL-1.1
    LICENSE_GFDL_1_1_INVARIANTS_ONLY,             // GFDL-1.1-invariants-only
    LICENSE_GFDL_1_1_INVARIANTS_OR_LATER,         // GFDL-1.1-invariants-or-later
    LICENSE_GFDL_1_1_NO_INVARIANTS_ONLY,          // GFDL-1.1-no-invariants-only
    LICENSE_GFDL_1_1_NO_INVARIANTS_OR_LATER,      // GFDL-1.1-no-invariants-or-later
    LICENSE_GFDL_1_1_ONLY,                        // GFDL-1.1-only
    LICENSE_GFDL_1_1_OR_LATER,                    // GFDL-1.1-or-later
    LICENSE_GFDL_1_2,                             // GFDL-1.2
    LICENSE_GFDL_1_2_INVARIANTS_ONLY,             // GFDL-1.2-invariants-only
    LICENSE_GFDL_1_2_INVARIANTS_OR_LATER,         // GFDL-1.2-invariants-or-later
    LICENSE_GFDL_1_2_NO_INVARIANTS_ONLY,          // GFDL-1.2-no-invariants-only
    LICENSE_GFDL_1_2_NO_INVARIANTS_OR_LATER,      // GFDL-1.2-no-invariants-or-later
    LICENSE_GFDL_1_2_ONLY,                        // GFDL-1.2-only
    LICENSE_GFDL_1_2_OR_LATER,                    // GFDL-1.2-or-later
    LICENSE_GFDL_1_3,                             // GFDL-1.3
    LICENSE_GFDL_1_3_INVARIANTS_ONLY,             // GFDL-1.3-invariants-only
    LICENSE_GFDL_1_3_INVARIANTS_OR_LATER,         // GFDL-1.3-invariants-or-later
    LICENSE_GFDL_1_3_NO_INVARIANTS_ONLY,          // GFDL-1.3-no-invariants-only
    LICENSE_GFDL_1_3_NO_INVARIANTS_OR_LATER,      // GFDL-1.3-no-invariants-or-later
    LICENSE_GFDL_1_3_ONLY,                        // GFDL-1.3-only
    LICENSE_GFDL_1_3_OR_LATER,                    // GFDL-1.3-or-later
    LICENSE_GIFTWARE,                             // Giftware
    LICENSE_GL2PS,                                // GL2PS
    LICENSE_GLIDE,                                // Glide
    LICENSE_GLULXE,                               // Glulxe
    LICENSE_GLWTPL,                               // GLWTPL
    LICENSE_GNUPLOT,                              // gnuplot
    LICENSE_GPL_1_0,                              // GPL-1.0
    LICENSE_GPL_1_0_PLUS,                         // GPL-1.0+
    LICENSE_GPL_1_0_ONLY,                         // GPL-1.0-only
    LICENSE_GPL_1_0_OR_LATER,                     // GPL-1.0-or-later
    LICENSE_GPL_2_0,                              // GPL-2.0
    LICENSE_GPL_2_0_PLUS,                         // GPL-2.0+
    LICENSE_GPL_2_0_ONLY,                         // GPL-2.0-only
    LICENSE_GPL_2_0_OR_LATER,                     // GPL-2.0-or-later
    LICENSE_GPL_2_0_WITH_AUTOCONF_EXCEPTION,      // GPL-2.0-with-autoconf-exception
    LICENSE_GPL_2_0_WITH_BISON_EXCEPTION,         // GPL-2.0-with-bison-exception
    LICENSE_GPL_2_0_WITH_CLASSPATH_EXCEPTION,     // GPL-2.0-with-classpath-exception
    LICENSE_GPL_2_0_WITH_FONT_EXCEPTION,          // GPL-2.0-with-font-exception
    LICENSE_GPL_2_0_WITH_GCC_EXCEPTION,           // GPL-2.0-with-GCC-exception
    LICENSE_GPL_3_0,                              // GPL-3.0
    LICENSE_GPL_3_0_PLUS,                         // GPL-3.0+
    LICENSE_GPL_3_0_ONLY,                         // GPL-3.0-only
    LICENSE_GPL_3_0_OR_LATER,                     // GPL-3.0-or-later
    LICENSE_GPL_3_0_WITH_AUTOCONF_EXCEPTION,      // GPL-3.0-with-autoconf-exception
    LICENSE_GPL_3_0_WITH_GCC_EXCEPTION,           // GPL-3.0-with-GCC-exception
    LICENSE_GRAPHICS_GEMS,                        // Graphics-Gems
    LICENSE_GSOAP_1_3B,                           // gSOAP-1.3b
    LICENSE_GTKBOOK,                              // gtkbook
    LICENSE_GUTMANN,                              // Gutmann
    LICENSE_HASKELLREPORT,                        // HaskellReport
    LICENSE_HDPARM,                               // hdparm
    LICENSE_HIDAPI,                               // HIDAPI
    LICENSE_HIPPOCRATIC_2_1,                      // Hippocratic-2.1
    LICENSE_HP_1986,                              // HP-1986
    LICENSE_HP_1989,                              // HP-1989
    LICENSE_HPND,                                 // HPND
    LICENSE_HPND_DEC,                             // HPND-DEC
    LICENSE_HPND_DOC,                             // HPND-doc
    LICENSE_HPND_DOC_SELL,                        // HPND-doc-sell
    LICENSE_HPND_EXPORT_US,                       // HPND-export-US
    LICENSE_HPND_EXPORT_US_ACKNOWLEDGEMENT,       // HPND-export-US-acknowledgement
    LICENSE_HPND_EXPORT_US_MODIFY,                // HPND-export-US-modify
    LICENSE_HPND_EXPORT2_US,                      // HPND-export2-US
    LICENSE_HPND_FENNEBERG_LIVINGSTON,            // HPND-Fenneberg-Livingston
    LICENSE_HPND_INRIA_IMAG,                      // HPND-INRIA-IMAG
    LICENSE_HPND_INTEL,                           // HPND-Intel
    LICENSE_HPND_KEVLIN_HENNEY,                   // HPND-Kevlin-Henney
    LICENSE_HPND_MARKUS_KUHN,                     // HPND-Markus-Kuhn
    LICENSE_HPND_MERCHANTABILITY_VARIANT,         // HPND-merchantability-variant
    LICENSE_HPND_MIT_DISCLAIMER,                  // HPND-MIT-disclaimer
    LICENSE_HPND_NETREK,                          // HPND-Netrek
    LICENSE_HPND_PBMPLUS,                         // HPND-Pbmplus
    LICENSE_HPND_SELL_MIT_DISCLAIMER_XSERVER,     // HPND-sell-MIT-disclaimer-xserver
    LICENSE_HPND_SELL_REGEXPR,                    // HPND-sell-regexpr
    LICENSE_HPND_SELL_VARIANT,                    // HPND-sell-variant
    LICENSE_HPND_SELL_VARIANT_MIT_DISCLAIMER,     // HPND-sell-variant-MIT-disclaimer
    LICENSE_HPND_SELL_VARIANT_MIT_DISCLAIMER_REV, // HPND-sell-variant-MIT-disclaimer-rev
    LICENSE_HPND_UC,                              // HPND-UC
    LICENSE_HPND_UC_EXPORT_US,                    // HPND-UC-export-US
    LICENSE_HTMLTIDY,                             // HTMLTIDY
    LICENSE_IBM_PIBS,                             // IBM-pibs
    LICENSE_ICU,                                  // ICU
    LICENSE_IEC_CODE_COMPONENTS_EULA,             // IEC-Code-Components-EULA
    LICENSE_IJG,                                  // IJG
    LICENSE_IJG_SHORT,                            // IJG-short
    LICENSE_IMAGEMAGICK,                          // ImageMagick
    LICENSE_IMATIX,                               // iMatix
    LICENSE_IMLIB2,                               // Imlib2
    LICENSE_INFO_ZIP,                             // Info-ZIP
    LICENSE_INNER_NET_2_0,                        // Inner-Net-2.0
    LICENSE_INNOSETUP,                            // InnoSetup
    LICENSE_INTEL,                                // Intel
    LICENSE_INTEL_ACPI,                           // Intel-ACPI
    LICENSE_INTERBASE_1_0,                        // Interbase-1.0
    LICENSE_IPA,                                  // IPA
    LICENSE_IPL_1_0,                              // IPL-1.0
    LICENSE_ISC,                                  // ISC
    LICENSE_ISC_VEILLARD,                         // ISC-Veillard
    LICENSE_JAM,                                  // Jam
    LICENSE_JASPER_2_0,                           // JasPer-2.0
    LICENSE_JPL_IMAGE,                            // JPL-image
    LICENSE_JPNIC,                                // JPNIC
    LICENSE_JSON,                                 // JSON
    LICENSE_KASTRUP,                              // Kastrup
    LICENSE_KAZLIB,                               // Kazlib
    LICENSE_KNUTH_CTAN,                           // Knuth-CTAN
    LICENSE_LAL_1_2,                              // LAL-1.2
    LICENSE_LAL_1_3,                              // LAL-1.3
    LICENSE_LATEX2E,                              // Latex2e
    LICENSE_LATEX2E_TRANSLATED_NOTICE,            // Latex2e-translated-notice
    LICENSE_LEPTONICA,                            // Leptonica
    LICENSE_LGPL_2_0,                             // LGPL-2.0
    LICENSE_LGPL_2_0_PLUS,                        // LGPL-2.0+
    LICENSE_LGPL_2_0_ONLY,                        // LGPL-2.0-only
    LICENSE_LGPL_2_0_OR_LATER,                    // LGPL-2.0-or-later
    LICENSE_LGPL_2_1,                             // LGPL-2.1
    LICENSE_LGPL_2_1_PLUS,                        // LGPL-2.1+
    LICENSE_LGPL_2_1_ONLY,                        // LGPL-2.1-only
    LICENSE_LGPL_2_1_OR_LATER,                    // LGPL-2.1-or-later
    LICENSE_LGPL_3_0,                             // LGPL-3.0
    LICENSE_LGPL_3_0_PLUS,                        // LGPL-3.0+
    LICENSE_LGPL_3_0_ONLY,                        // LGPL-3.0-only
    LICENSE_LGPL_3_0_OR_LATER,                    // LGPL-3.0-or-later
    LICENSE_LGPLLR,                               // LGPLLR
    LICENSE_LIBPNG,                               // Libpng
    LICENSE_LIBPNG_2_0,                           // libpng-2.0
    LICENSE_LIBSELINUX_1_0,                       // libselinux-1.0
    LICENSE_LIBTIFF,                              // libtiff
    LICENSE_LIBUTIL_DAVID_NUGENT,                 // libutil-David-Nugent
    LICENSE_LILIQ_P_1_1,                          // LiLiQ-P-1.1
    LICENSE_LILIQ_R_1_1,                          // LiLiQ-R-1.1
    LICENSE_LILIQ_RPLUS_1_1,                      // LiLiQ-Rplus-1.1
    LICENSE_LINUX_MAN_PAGES_1_PARA,               // Linux-man-pages-1-para
    LICENSE_LINUX_MAN_PAGES_COPYLEFT,             // Linux-man-pages-copyleft
    LICENSE_LINUX_MAN_PAGES_COPYLEFT_2_PARA,      // Linux-man-pages-copyleft-2-para
    LICENSE_LINUX_MAN_PAGES_COPYLEFT_VAR,         // Linux-man-pages-copyleft-var
    LICENSE_LINUX_OPENIB,                         // Linux-OpenIB
    LICENSE_LOOP,                                 // LOOP
    LICENSE_LPD_DOCUMENT,                         // LPD-document
    LICENSE_LPL_1_0,                              // LPL-1.0
    LICENSE_LPL_1_02,                             // LPL-1.02
    LICENSE_LPPL_1_0,                             // LPPL-1.0
    LICENSE_LPPL_1_1,                             // LPPL-1.1
    LICENSE_LPPL_1_2,                             // LPPL-1.2
    LICENSE_LPPL_1_3A,                            // LPPL-1.3a
    LICENSE_LPPL_1_3C,                            // LPPL-1.3c
    LICENSE_LSOF,                                 // lsof
    LICENSE_LUCIDA_BITMAP_FONTS,                  // Lucida-Bitmap-Fonts
    LICENSE_LZMA_SDK_9_11_TO_9_20,                // LZMA-SDK-9.11-to-9.20
    LICENSE_LZMA_SDK_9_22,                        // LZMA-SDK-9.22
    LICENSE_MACKERRAS_3_CLAUSE,                   // Mackerras-3-Clause
    LICENSE_MACKERRAS_3_CLAUSE_ACKNOWLEDGMENT,    // Mackerras-3-Clause-acknowledgment
    LICENSE_MAGAZ,                                // magaz
    LICENSE_MAILPRIO,                             // mailprio
    LICENSE_MAKEINDEX,                            // MakeIndex
    LICENSE_MARTIN_BIRGMEIER,                     // Martin-Birgmeier
    LICENSE_MCPHEE_SLIDESHOW,                     // McPhee-slideshow
    LICENSE_METAMAIL,                             // metamail
    LICENSE_MINPACK,                              // Minpack
    LICENSE_MIPS,                                 // MIPS
    LICENSE_MIROS,                                // MirOS
    LICENSE_MIT,                                  // MIT
    LICENSE_MIT_0,                                // MIT-0
    LICENSE_MIT_ADVERTISING,                      // MIT-advertising
    LICENSE_MIT_CLICK,                            // MIT-Click
    LICENSE_MIT_CMU,                              // MIT-CMU
    LICENSE_MIT_ENNA,                             // MIT-enna
    LICENSE_MIT_FEH,                              // MIT-feh
    LICENSE_MIT_FESTIVAL,                         // MIT-Festival
    LICENSE_MIT_KHRONOS_OLD,                      // MIT-Khronos-old
    LICENSE_MIT_MODERN_VARIANT,                   // MIT-Modern-Variant
    LICENSE_MIT_OPEN_GROUP,                       // MIT-open-group
    LICENSE_MIT_TESTREGEX,                        // MIT-testregex
    LICENSE_MIT_WU,                               // MIT-Wu
    LICENSE_MITNFA,                               // MITNFA
    LICENSE_MMIXWARE,                             // MMIXware
    LICENSE_MOTOSOTO,                             // Motosoto
    LICENSE_MPEG_SSG,                             // MPEG-SSG
    LICENSE_MPI_PERMISSIVE,                       // mpi-permissive
    LICENSE_MPICH2,                               // mpich2
    LICENSE_MPL_1_0,                              // MPL-1.0
    LICENSE_MPL_1_1,                              // MPL-1.1
    LICENSE_MPL_2_0,                              // MPL-2.0
    LICENSE_MPL_2_0_NO_COPYLEFT_EXCEPTION,        // MPL-2.0-no-copyleft-exception
    LICENSE_MPLUS,                                // mplus
    LICENSE_MS_LPL,                               // MS-LPL
    LICENSE_MS_PL,                                // MS-PL
    LICENSE_MS_RL,                                // MS-RL
    LICENSE_MTLL,                                 // MTLL
    LICENSE_MULANPSL_1_0,                         // MulanPSL-1.0
    LICENSE_MULANPSL_2_0,                         // MulanPSL-2.0
    LICENSE_MULTICS,                              // Multics
    LICENSE_MUP,                                  // Mup
    LICENSE_NAIST_2003,                           // NAIST-2003
    LICENSE_NASA_1_3,                             // NASA-1.3
    LICENSE_NAUMEN,                               // Naumen
    LICENSE_NBPL_1_0,                             // NBPL-1.0
    LICENSE_NCBI_PD,                              // NCBI-PD
    LICENSE_NCGL_UK_2_0,                          // NCGL-UK-2.0
    LICENSE_NCL,                                  // NCL
    LICENSE_NCSA,                                 // NCSA
    LICENSE_NET_SNMP,                             // Net-SNMP
    LICENSE_NETCDF,                               // NetCDF
    LICENSE_NEWSLETR,                             // Newsletr
    LICENSE_NGPL,                                 // NGPL
    LICENSE_NICTA_1_0,                            // NICTA-1.0
    LICENSE_NIST_PD,                              // NIST-PD
    LICENSE_NIST_PD_FALLBACK,                     // NIST-PD-fallback
    LICENSE_NIST_SOFTWARE,                        // NIST-Software
    LICENSE_NLOD_1_0,                             // NLOD-1.0
    LICENSE_NLOD_2_0,                             // NLOD-2.0
    LICENSE_NLPL,                                 // NLPL
    LICENSE_NOKIA,                                // Nokia
    LICENSE_NOSL,                                 // NOSL
    LICENSE_NOWEB,                                // Noweb
    LICENSE_NPL_1_0,                              // NPL-1.0
    LICENSE_NPL_1_1,                              // NPL-1.1
    LICENSE_NPOSL_3_0,                            // NPOSL-3.0
    LICENSE_NRL,                                  // NRL
    LICENSE_NTP,                                  // NTP
    LICENSE_NTP_0,                                // NTP-0
    LICENSE_NUNIT,                                // Nunit
    LICENSE_O_UDA_1_0,                            // O-UDA-1.0
    LICENSE_OAR,                                  // OAR
    LICENSE_OCCT_PL,                              // OCCT-PL
    LICENSE_OCLC_2_0,                             // OCLC-2.0
    LICENSE_ODBL_1_0,                             // ODbL-1.0
    LICENSE_ODC_BY_1_0,                           // ODC-By-1.0
    LICENSE_OFFIS,                                // OFFIS
    LICENSE_OFL_1_0,                              // OFL-1.0
    LICENSE_OFL_1_0_NO_RFN,                       // OFL-1.0-no-RFN
    LICENSE_OFL_1_0_RFN,                          // OFL-1.0-RFN
    LICENSE_OFL_1_1,                              // OFL-1.1
    LICENSE_OFL_1_1_NO_RFN,                       // OFL-1.1-no-RFN
    LICENSE_OFL_1_1_RFN,                          // OFL-1.1-RFN
    LICENSE_OGC_1_0,                              // OGC-1.0
    LICENSE_OGDL_TAIWAN_1_0,                      // OGDL-Taiwan-1.0
    LICENSE_OGL_CANADA_2_0,                       // OGL-Canada-2.0
    LICENSE_OGL_UK_1_0,                           // OGL-UK-1.0
    LICENSE_OGL_UK_2_0,                           // OGL-UK-2.0
    LICENSE_OGL_UK_3_0,                           // OGL-UK-3.0
    LICENSE_OGTSL,                                // OGTSL
    LICENSE_OLDAP_1_1,                            // OLDAP-1.1
    LICENSE_OLDAP_1_2,                            // OLDAP-1.2
    LICENSE_OLDAP_1_3,                            // OLDAP-1.3
    LICENSE_OLDAP_1_4,                            // OLDAP-1.4
    LICENSE_OLDAP_2_0,                            // OLDAP-2.0
    LICENSE_OLDAP_2_0_1,                          // OLDAP-2.0.1
    LICENSE_OLDAP_2_1,                            // OLDAP-2.1
    LICENSE_OLDAP_2_2,                            // OLDAP-2.2
    LICENSE_OLDAP_2_2_1,                          // OLDAP-2.2.1
    LICENSE_OLDAP_2_2_2,                          // OLDAP-2.2.2
    LICENSE_OLDAP_2_3,                            // OLDAP-2.3
    LICENSE_OLDAP_2_4,                            // OLDAP-2.4
    LICENSE_OLDAP_2_5,                            // OLDAP-2.5
    LICENSE_OLDAP_2_6,                            // OLDAP-2.6
    LICENSE_OLDAP_2_7,                            // OLDAP-2.7
    LICENSE_OLDAP_2_8,                            // OLDAP-2.8
    LICENSE_OLFL_1_3,                             // OLFL-1.3
    LICENSE_OML,                                  // OML
    LICENSE_OPENPBS_2_3,                          // OpenPBS-2.3
    LICENSE_OPENSSL,                              // OpenSSL
    LICENSE_OPENSSL_STANDALONE,                   // OpenSSL-standalone
    LICENSE_OPENVISION,                           // OpenVision
    LICENSE_OPL_1_0,                              // OPL-1.0
    LICENSE_OPL_UK_3_0,                           // OPL-UK-3.0
    LICENSE_OPUBL_1_0,                            // OPUBL-1.0
    LICENSE_OSET_PL_2_1,                          // OSET-PL-2.1
    LICENSE_OSL_1_0,                              // OSL-1.0
    LICENSE_OSL_1_1,                              // OSL-1.1
    LICENSE_OSL_2_0,                              // OSL-2.0
    LICENSE_OSL_2_1,                              // OSL-2.1
    LICENSE_OSL_3_0,                              // OSL-3.0
    LICENSE_PADL,                                 // PADL
    LICENSE_PARITY_6_0_0,                         // Parity-6.0.0
    LICENSE_PARITY_7_0_0,                         // Parity-7.0.0
    LICENSE_PDDL_1_0,                             // PDDL-1.0
    LICENSE_PHP_3_0,                              // PHP-3.0
    LICENSE_PHP_3_01,                             // PHP-3.01
    LICENSE_PIXAR,                                // Pixar
    LICENSE_PKGCONF,                              // pkgconf
    LICENSE_PLEXUS,                               // Plexus
    LICENSE_PNMSTITCH,                            // pnmstitch
    LICENSE_POLYFORM_NONCOMMERCIAL_1_0_0,         // PolyForm-Noncommercial-1.0.0
    LICENSE_POLYFORM_SMALL_BUSINESS_1_0_0,        // PolyForm-Small-Business-1.0.0
    LICENSE_POSTGRESQL,                           // PostgreSQL
    LICENSE_PPL,                                  // PPL
    LICENSE_PSF_2_0,                              // PSF-2.0
    LICENSE_PSFRAG,                               // psfrag
    LICENSE_PSUTILS,                              // psutils
    LICENSE_PYTHON_2_0,                           // Python-2.0
    LICENSE_PYTHON_2_0_1,                         // Python-2.0.1
    LICENSE_PYTHON_LDAP,                          // python-ldap
    LICENSE_QHULL,                                // Qhull
    LICENSE_QPL_1_0,                              // QPL-1.0
    LICENSE_QPL_1_0_INRIA_2004,                   // QPL-1.0-INRIA-2004
    LICENSE_RADVD,                                // radvd
    LICENSE_RDISC,                                // Rdisc
    LICENSE_RHECOS_1_1,                           // RHeCos-1.1
    LICENSE_RPL_1_1,                              // RPL-1.1
    LICENSE_RPL_1_5,                              // RPL-1.5
    LICENSE_RPSL_1_0,                             // RPSL-1.0
    LICENSE_RSA_MD,                               // RSA-MD
    LICENSE_RSCPL,                                // RSCPL
    LICENSE_RUBY,                                 // Ruby
    LICENSE_RUBY_PTY,                             // Ruby-pty
    LICENSE_SAX_PD,                               // SAX-PD
    LICENSE_SAX_PD_2_0,                           // SAX-PD-2.0
    LICENSE_SAXPATH,                              // Saxpath
    LICENSE_SCEA,                                 // SCEA
    LICENSE_SCHEMEREPORT,                         // SchemeReport
    LICENSE_SENDMAIL,                             // Sendmail
    LICENSE_SENDMAIL_8_23,                        // Sendmail-8.23
    LICENSE_SENDMAIL_OPEN_SOURCE_1_1,             // Sendmail-Open-Source-1.1
    LICENSE_SGI_B_1_0,                            // SGI-B-1.0
    LICENSE_SGI_B_1_1,                            // SGI-B-1.1
    LICENSE_SGI_B_2_0,                            // SGI-B-2.0
    LICENSE_SGI_OPENGL,                           // SGI-OpenGL
    LICENSE_SGP4,                                 // SGP4
    LICENSE_SHL_0_5,                              // SHL-0.5
    LICENSE_SHL_0_51,                             // SHL-0.51
    LICENSE_SIMPL_2_0,                            // SimPL-2.0
    LICENSE_SISSL,                                // SISSL
    LICENSE_SISSL_1_2,                            // SISSL-1.2
    LICENSE_SL,                                   // SL
    LICENSE_SLEEPYCAT,                            // Sleepycat
    LICENSE_SMAIL_GPL,                            // SMAIL-GPL
    LICENSE_SMLNJ,                                // SMLNJ
    LICENSE_SMPPL,                                // SMPPL
    LICENSE_SNIA,                                 // SNIA
    LICENSE_SNPRINTF,                             // snprintf
    LICENSE_SOFTSURFER,                           // softSurfer
    LICENSE_SOUNDEX,                              // Soundex
    LICENSE_SPENCER_86,                           // Spencer-86
    LICENSE_SPENCER_94,                           // Spencer-94
    LICENSE_SPENCER_99,                           // Spencer-99
    LICENSE_SPL_1_0,                              // SPL-1.0
    LICENSE_SSH_KEYSCAN,                          // ssh-keyscan
    LICENSE_SSH_OPENSSH,                          // SSH-OpenSSH
    LICENSE_SSH_SHORT,                            // SSH-short
    LICENSE_SSLEAY_STANDALONE,                    // SSLeay-standalone
    LICENSE_SSPL_1_0,                             // SSPL-1.0
    LICENSE_STANDARDML_NJ,                        // StandardML-NJ
    LICENSE_SUGARCRM_1_1_3,                       // SugarCRM-1.1.3
    LICENSE_SUN_PPP,                              // Sun-PPP
    LICENSE_SUN_PPP_2000,                         // Sun-PPP-2000
    LICENSE_SUNPRO,                               // SunPro
    LICENSE_SWL,                                  // SWL
    LICENSE_SWRULE,                               // swrule
    LICENSE_SYMLINKS,                             // Symlinks
    LICENSE_TAPR_OHL_1_0,                         // TAPR-OHL-1.0
    LICENSE_TCL,                                  // TCL
    LICENSE_TCP_WRAPPERS,                         // TCP-wrappers
    LICENSE_TERMREADKEY,                          // TermReadKey
    LICENSE_TGPPL_1_0,                            // TGPPL-1.0
    LICENSE_THIRDEYE,                             // ThirdEye
    LICENSE_THREEPARTTABLE,                       // threeparttable
    LICENSE_TMATE,                                // TMate
    LICENSE_TORQUE_1_1,                           // TORQUE-1.1
    LICENSE_TOSL,                                 // TOSL
    LICENSE_TPDL,                                 // TPDL
    LICENSE_TPL_1_0,                              // TPL-1.0
    LICENSE_TRUSTEDQSL,                           // TrustedQSL
    LICENSE_TTWL,                                 // TTWL
    LICENSE_TTYP0,                                // TTYP0
    LICENSE_TU_BERLIN_1_0,                        // TU-Berlin-1.0
    LICENSE_TU_BERLIN_2_0,                        // TU-Berlin-2.0
    LICENSE_UBUNTU_FONT_1_0,                      // Ubuntu-font-1.0
    LICENSE_UCAR,                                 // UCAR
    LICENSE_UCL_1_0,                              // UCL-1.0
    LICENSE_ULEM,                                 // ulem
    LICENSE_UMICH_MERIT,                          // UMich-Merit
    LICENSE_UNICODE_3_0,                          // Unicode-3.0
    LICENSE_UNICODE_DFS_2015,                     // Unicode-DFS-2015
    LICENSE_UNICODE_DFS_2016,                     // Unicode-DFS-2016
    LICENSE_UNICODE_TOU,                          // Unicode-TOU
    LICENSE_UNIXCRYPT,                            // UnixCrypt
    LICENSE_UNLICENSE,                            // Unlicense
    LICENSE_UPL_1_0,                              // UPL-1.0
    LICENSE_URT_RLE,                              // URT-RLE
    LICENSE_VIM,                                  // Vim
    LICENSE_VOSTROM,                              // VOSTROM
    LICENSE_VSL_1_0,                              // VSL-1.0
    LICENSE_W3C,                                  // W3C
    LICENSE_W3C_19980720,                         // W3C-19980720
    LICENSE_W3C_20150513,                         // W3C-20150513
    LICENSE_W3M,                                  // w3m
    LICENSE_WATCOM_1_0,                           // Watcom-1.0
    LICENSE_WIDGET_WORKSHOP,                      // Widget-Workshop
    LICENSE_WSUIPA,                               // Wsuipa
    LICENSE_WTFPL,                                // WTFPL
    LICENSE_WWL,                                  // wwl
    LICENSE_WXWINDOWS,                            // wxWindows
    LICENSE_X11,                                  // X11
    LICENSE_X11_DISTRIBUTE_MODIFICATIONS_VARIANT, // X11-distribute-modifications-variant
    LICENSE_X11_SWAPPED,                          // X11-swapped
    LICENSE_XDEBUG_1_03,                          // Xdebug-1.03
    LICENSE_XEROX,                                // Xerox
    LICENSE_XFIG,                                 // Xfig
    LICENSE_XFREE86_1_1,                          // XFree86-1.1
    LICENSE_XINETD,                               // xinetd
    LICENSE_XKEYBOARD_CONFIG_ZINOVIEV,            // xkeyboard-config-Zinoviev
    LICENSE_XLOCK,                                // xlock
    LICENSE_XNET,                                 // Xnet
    LICENSE_XPP,                                  // xpp
    LICENSE_XSKAT,                                // XSkat
    LICENSE_XZOOM,                                // xzoom
    LICENSE_YPL_1_0,                              // YPL-1.0
    LICENSE_YPL_1_1,                              // YPL-1.1
    LICENSE_ZED,                                  // Zed
    LICENSE_ZEEFF,                                // Zeeff
    LICENSE_ZEND_2_0,                             // Zend-2.0
    LICENSE_ZIMBRA_1_3,                           // Zimbra-1.3
    LICENSE_ZIMBRA_1_4,                           // Zimbra-1.4
    LICENSE_ZLIB,                                 // Zlib
    LICENSE_ZLIB_ACKNOWLEDGEMENT,                 // zlib-acknowledgement
    LICENSE_ZPL_1_1,                              // ZPL-1.1
    LICENSE_ZPL_2_0,                              // ZPL-2.0
    LICENSE_ZPL_2_1                               // ZPL-2.1
};

/// @brief get license from str
/// @param str
/// @return license
license_t license_from_str(const char *str);

/// @brief convert license to string
/// @param license
/// @return str
const char *license_to_string(license_t license);

#endif // CREN_MANIFEST_LICENSE_H
