name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        cmake-generator: [Ninja, "Unix Makefiles"]

    steps:
      # Checkout repository
      - name: Checkout source
        uses: actions/checkout@v4

      # Install dependencies (Linux)
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update || true
          sudo apt-get install -y cmake ninja-build gcc g++ || true

      # Install dependencies (macOS)
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install cmake ninja

      # Install dependencies (Windows)
      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ninja -y
          choco install mingw -y
          echo "Using GCC from MinGW"
          export PATH="/c/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin:$PATH"

      # Create build directory
      - name: Create build directory
        run: cmake -B build -S . -G "${{ matrix.cmake-generator }}" -DCMAKE_BUILD_TYPE=Release

      # Build project
      - name: Build
        run: cmake --build build --config Release
